name: lakes6
description: >-
  Sample app from "Building Layouts", https://docs.flutter.dev/ui/layout.
version: 1.0.0

#resolution: workspace
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  speech_to_text: ^6.5.1
  image_picker: ^1.0.7
  tflite: ^1.1.2
  http: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.2
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  flutter_local_notifications: ^16.3.2
  fl_chart: ^0.66.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  flutter_svg: ^2.0.10+1
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  hive: ^2.2.3
  permission_handler: ^11.3.0
  connectivity_plus: ^5.0.2
  flutter_markdown: ^0.6.18+3
  table_calendar: ^3.0.9
  flutter_bluetooth_serial: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - img/
    - assets/